codes/urls.py
from django.urls import path

from . import views

app_name = 'codes'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_index>/', views.detail, name = 'detail'),
    path('<int:question_index>/user_rating/', views.user_rating, name = 'user_rating'),
]

codes/models.py
from django.db import models

class Question(models.Model):
    question_header = models.CharField(max_length = 50)
    question_text = models.CharField(max_length = 200)
    question_index = models.IntegerField(primary_key=True)
    user_rating = models.IntegerField(default = 0)
    answer_text = models.CharField(max_length = 200)
    def __str__(self):
        return self.question_text

# Create your models here.

codes/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import Question
from django.template import loader
from django.urls import reverse


def index(request):
    first_few = Question.objects.all()
    context = {'first_few' : first_few, }
    return render(request, 'codes/index.html', context)

def detail(request, question_index):
    question = get_object_or_404(Question, pk = question_index)
    return render(request, 'codes/detail.html', {'question' : question})


def user_rating(request, question_index):
    question = get_object_or_404(Question, pk = question_index)
    try:
        selected_choice = request.POST['choice']
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'codes/detail.html',
        {'question' : question,
        'error_message' : "You didn't select a choice.",
        })
    else:
        if selected_choice == 'YES':
            question.user_rating += 1
            question.save()
        else:
            question.user_rating -= 1
            question.save()
        return render(request, 'codes/results.html', {'question' : question})


def results(request, question_index):
    question = get_object_or_404(Question, pk=question_index)
    return render(request, 'codes/results.html', {'question': question})

codes/templates/codes/detail.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{{ question.question_header }}</title>
  </head>
  <body style="background-image: url('https://cdn.wallpapersafari.com/23/50/P0rIL6.jpg'); background-size: cover;">

    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
      <a class="navbar-brand" href="{%url 'codes:index' %}"> <img src="bg.jpg" alt="FlashMeM" ></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{%url 'codes:index' %}"><img src="/open-iconic/svg/home.svg" alt="Home"><span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/admin">Admin</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://github.com/arjunmann73/FlashMeM">Github</a>
          </li>
      </ul>
      </div>
    </nav>
    <br>

  <div class="card text-white bg-warning mx-auto text-center w-50">
  <h5 class="card-header">{{ question.question_header }}</h5>
  <div class="card-body">
    <h5 class="card-title">{{ question.question_text }}</h5>
    <p class="card-text">{{ question.answer_text }}</p>
    <form action="{% url 'codes:user_rating' question.question_index %}" method="post">
    {% csrf_token %}
    <button class="btn btn-success" name='choice' type="submit" value='YES' >+1</button>
    <button class="btn btn-danger" name='choice' type="submit" value='NO' >-1</button>
    </form>
    </div>
  </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

codes/templates/codes/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>FlashMeM : home</title>
  </head>
  <body style="background-image: url('https://cdn.wallpapersafari.com/23/50/P0rIL6.jpg'); background-size: cover;">

    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
      <a class="navbar-brand" href="{%url 'codes:index' %}"><img src="logo.jpg" alt="FlashMeM"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{%url 'codes:index' %}"><img src="/open-iconic/svg/home.svg" alt="Home"><span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/admin">Admin</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://github.com/arjunmann73/FlashMeM">Github</a>
          </li>
      </ul>
      </div>
    </nav>
    <br>
    <div class="card-columns">
    {% if first_few %}
      {% for question in first_few %}
      <div class="card text-{% cycle 'white' 'white' 'white' 'white' 'white' 'white' 'black' 'white' %} bg-{% cycle 'primary' 'secondary' 'success' 'danger' 'warning' 'info' 'light' 'dark' %} mb-3 w-75">
        <div class="card-header">{{ question.question_index }}. {{ question.question_header }}</div>
        <div class="card-body">
          <p class="card-text">{{ question.question_text }}</p>
          <a href="{% url 'codes:detail' question.question_index %}" class="btn btn-{% cycle 'light' 'primary' 'secondary' 'dark' 'light' 'dark' 'dark' 'light'%}">Answer</a>
        </div>
      </div>

      {% endfor %}
    {% endif %}
      </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

codes/templates/codes/results.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>User rating!</title>
  </head>
  <body style="background-image: url('https://cdn.wallpapersafari.com/23/50/P0rIL6.jpg'); background-size: cover;">
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
      <a class="navbar-brand" href="{%url 'codes:index' %}"><img src="logo.jpg" alt="FlashMeM"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{%url 'codes:index' %}"><img src="/open-iconic/svg/home.svg" alt="Home"><span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/admin">Admin</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://github.com/arjunmann73/FlashMeM">Github</a>
          </li>
      </ul>
      </div>
    </nav>
    <br>

    <div class="card text-white bg-warning mx-auto text-center w-50">
    <h5 class="card-header">{{ question.question_header }}</h5>
    <div class="card-body">
      <h5 class="card-title">{{ question.question_text }}</h5>
      <p class="card-text">Rating of the question is: {{ question.user_rating }}</p>
        <a class="btn btn-primary" href="{% url 'codes:detail' question.question_index %}" role="button">Vote again?</a>
      </div>
    </div>

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>